apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: student-info-app
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend  # The SecretStore you have configured
    kind: SecretStore    # The resource type of the SecretStore
  target:
    name: example-secret     # The name of the Kubernetes secret to be created
  data:
  - secretKey: DB_username  # The key inside the target Kubernetes secret
    remoteRef:
      key: argocd/data/mysecret  # The path in Vault
      property: DB_username     # The specific field inside the Vault secret to be fetched
  - secretKey: DB_password  # The key inside the target Kubernetes secret
    remoteRef:
      key: argocd/data/mysecret  # The path in Vault
      property: DB_password     # The specific field inside the Vault secret to be fetched
  - secretKey: DB_URL  # The key inside the target Kubernetes secret
    remoteRef:
      key: argocd/data/mysecret  # The path in Vault
      property: DB_URL           # The specific field inside the Vault secret to be fetched