apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: student-info-app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "argocd"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "vault-token"
            namespace: "student-info-app"
            key: "role-id"
          secretRef:
            name: "vault-token"
            namespace: "student-info-app"
            key: "secret-id"