apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-info-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Node affinity to schedule on node with role=database
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: student-info-app
                operator: In
                values:
                - "true"
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: DB_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: DB_password
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: DB_URL
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: student-info-app
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
