name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # or your desired branch
    paths:
      - '**/cmd/**' # Only trigger for changes in the cmd directory
      - '**/internal/**' # Include other relevant code directories if applicable

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 
            - "${{ secrets.DOCKERHUB_USERNAME }}/student-api:${{github.run_id}}"
